# Generated by Django 4.0 on 2022-10-07 09:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Имя')),
                ('surname', models.CharField(max_length=300, verbose_name='Фамилия')),
                ('actor_photo', models.ImageField(upload_to='images/actors', verbose_name='Фото актера')),
                ('birthday', models.DateField(null=True, verbose_name='День рожденья')),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=300, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_title', models.CharField(max_length=300, verbose_name='Название фильма')),
                ('film_preview', models.ImageField(upload_to='images/films', verbose_name='Превью фильма')),
                ('film_year', models.CharField(max_length=50, verbose_name='Дата выхода фильма')),
                ('film_type', models.CharField(max_length=50, verbose_name='Тип')),
                ('description', models.TextField()),
                ('film_file', models.FileField(upload_to='video/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])])),
                ('actor_film_list', models.ManyToManyField(to='films.Actor')),
                ('film_list', models.ManyToManyField(to='films.Categories')),
            ],
        ),
    ]
