# Generated by Django 4.1.1 on 2022-09-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_title', models.CharField(max_length=300, verbose_name='Название фильма')),
                ('film_preview', models.FileField(upload_to='', verbose_name='Превью фильма')),
                ('film_catergory', models.CharField(max_length=200, verbose_name='Категория фильма')),
                ('film_year', models.CharField(max_length=50, verbose_name='Дата выхода фильма')),
            ],
        ),
    ]
