# Generated by Django 4.1.2 on 2022-10-25 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='film_type',
        ),
    ]
