# Generated by Django 4.1.1 on 2022-09-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='film_type',
            field=models.CharField(default=0, max_length=50, verbose_name='Тип'),
            preserve_default=False,
        ),
    ]
