# Generated by Django 4.1.1 on 2022-09-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_film_film_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='film_preview',
            field=models.ImageField(upload_to='', verbose_name='Превью фильма'),
        ),
    ]
