# Generated by Django 4.1.2 on 2022-10-25 10:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_remove_film_film_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_title', models.CharField(max_length=300, verbose_name='Название сериала')),
                ('series_preview', models.ImageField(upload_to='images/films', verbose_name='Превью сериала')),
                ('series_year', models.CharField(max_length=50, verbose_name='Дата выхода сериала')),
                ('description', models.TextField()),
                ('series_count', models.IntegerField(verbose_name='Кол-во серий')),
                ('series_file', models.FileField(upload_to='video/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])])),
                ('actor_film_list', models.ManyToManyField(to='films.actor')),
                ('film_list', models.ManyToManyField(to='films.categories')),
            ],
        ),
    ]
