# Generated by Django 4.1.2 on 2022-10-25 10:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_alter_seriesvideo_series_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='seasons_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во сезонов'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seriesvideo',
            name='series_file',
            field=models.FileField(upload_to='video/series/<django.db.models.query_utils.DeferredAttribute object at 0x00000286846F3970>', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])]),
        ),
    ]
