# Generated by Django 4.1.1 on 2022-09-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0010_alter_film_film_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='film_preview',
            field=models.ImageField(height_field=50, upload_to='images/films', verbose_name='Превью фильма', width_field=50),
        ),
    ]
