# Generated by Django 4.1.2 on 2022-11-01 14:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0012_alter_seriesvideo_series_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seriesvideo',
            name='series_ind',
        ),
        migrations.AddField(
            model_name='series',
            name='series_list',
            field=models.ManyToManyField(to='films.seriesvideo'),
        ),
        migrations.AlterField(
            model_name='seriesvideo',
            name='series_file',
            field=models.FileField(upload_to='video/series/<django.db.models.query_utils.DeferredAttribute object at 0x7ff77327e590>', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])]),
        ),
    ]
