# Generated by Django 4.1.1 on 2022-09-26 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0012_alter_film_film_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='film_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='films.film'),
            preserve_default=False,
        ),
    ]
