# Generated by Django 4.1.1 on 2022-09-26 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0013_film_film_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='film_id',
        ),
    ]
