# Generated by Django 4.1.1 on 2022-09-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0014_remove_film_film_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='film_preview',
            field=models.ImageField(upload_to='', verbose_name='Превью фильма'),
        ),
    ]
