# Generated by Django 4.1.1 on 2022-09-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0015_alter_film_film_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='film_preview',
            field=models.ImageField(upload_to='images/films', verbose_name='Превью фильма'),
        ),
    ]
