# Generated by Django 4.1.1 on 2022-10-03 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0017_film_description_film_film_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='actors',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
