# Generated by Django 4.1.1 on 2022-10-04 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0018_film_actors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Имя')),
                ('surname', models.CharField(max_length=300, verbose_name='Фамилия')),
                ('actor_photo', models.ImageField(upload_to='images/actors', verbose_name='Фото актера')),
                ('actor_film_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.film')),
            ],
        ),
    ]
