# Generated by Django 4.1.1 on 2022-10-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0019_actor'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='birthday',
            field=models.CharField(default=0, max_length=300, verbose_name='День рожденья'),
            preserve_default=False,
        ),
    ]
