# Generated by Django 4.1.1 on 2022-10-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0020_actor_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='birthday',
            field=models.DateField(verbose_name='День рожденья'),
        ),
    ]
