# Generated by Django 4.1.1 on 2022-10-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0023_remove_actor_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='birthday',
            field=models.DateField(null=True, verbose_name='День рожденья'),
        ),
    ]
