# Generated by Django 4.1.1 on 2022-10-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0024_actor_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='actor_film_list',
        ),
        migrations.AddField(
            model_name='actor',
            name='actor_film_list',
            field=models.ManyToManyField(to='films.film'),
        ),
    ]
