# Generated by Django 4.1.1 on 2022-10-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0025_remove_actor_actor_film_list_actor_actor_film_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=300, verbose_name='Название')),
                ('film_list', models.ManyToManyField(to='films.film')),
            ],
        ),
    ]
