# Generated by Django 4.1.1 on 2022-10-04 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0026_categorise'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorise',
            new_name='Categories',
        ),
    ]
