# Generated by Django 4.1.2 on 2022-10-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0027_rename_categorise_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='actor_film_list',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='film_list',
        ),
        migrations.AddField(
            model_name='film',
            name='actor_film_list',
            field=models.ManyToManyField(to='films.actor'),
        ),
        migrations.AddField(
            model_name='film',
            name='film_list',
            field=models.ManyToManyField(to='films.categories'),
        ),
    ]
