# Generated by Django 4.0 on 2022-10-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0028_remove_actor_actor_film_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='actor_film_list',
            field=models.ManyToManyField(to='films.Actor'),
        ),
        migrations.AlterField(
            model_name='film',
            name='film_list',
            field=models.ManyToManyField(to='films.Categories'),
        ),
    ]
