# Generated by Django 4.1.2 on 2022-11-02 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0031_seriesvideo_series_season_ind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seriesvideo',
            name='series_season_ind',
        ),
    ]
