# Generated by Django 4.1.2 on 2022-11-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0032_remove_seriesvideo_series_season_ind'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='tag',
            field=models.TextField(default='Фильм', verbose_name='tag'),
        ),
        migrations.AddField(
            model_name='series',
            name='tag',
            field=models.TextField(default='Сериал', verbose_name='tag'),
        ),
    ]
