# Generated by Django 4.1.2 on 2022-11-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0034_alter_film_tag_alter_series_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='tag',
            field=models.TextField(default='Сериал', max_length=50, verbose_name='Тэг'),
        ),
    ]
