# Generated by Django 4.1.2 on 2022-11-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0035_alter_series_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='tag',
            field=models.CharField(default='Фильм', max_length=50, verbose_name='Тэг'),
        ),
        migrations.AlterField(
            model_name='series',
            name='tag',
            field=models.CharField(default='Сериал', max_length=50, verbose_name='Тэг'),
        ),
    ]
