# Generated by Django 4.1.2 on 2022-11-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0037_alter_series_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='tag',
            field=models.CharField(choices=[('a', 'Сериал'), ('b', 'Мультсериал')], default='Сериал', max_length=1, verbose_name='Тэг'),
        ),
    ]
