# Generated by Django 4.1.2 on 2022-11-08 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('films', '0039_alter_film_tag_alter_series_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='tag',
            field=models.CharField(choices=[('1', 'Фильм'), ('2', 'Мультфильм')], max_length=1, verbose_name='Тэг'),
        ),
        migrations.AlterField(
            model_name='series',
            name='tag',
            field=models.CharField(choices=[('1', 'Сериал'), ('2', 'Мультсериал')], max_length=1, verbose_name='Тэг'),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.film')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.series')),
            ],
        ),
    ]
